@extends('layout.site')
@section('appContents')
    <h1>About</h1>
    <h4>Isayama was born in Ōyama, Ōita Prefecture, Japan, which is now part of Hita. He was attending Hita Rinko Senior High School when he began submitting manga works to contests.[3] After graduating, he matriculated in the manga design program of the arts department at Kyushu Designer Gakuen. In 2006, he applied for the Magazine Grand Prix known as MGP promoted by Kodansha Ltd. and a short version of Attack on Titan (Shingeki no Kyojin) was given the "Fine Work" award.[4] At age twenty, he moved to Tokyo and worked at an Internet café in order to pursue a career in writing manga.[5] This one-shot would later be included with the first Blu-ray of the anime adaptation.[6]

Originally, he offered his work to the Weekly Shōnen Jump department at Shueisha, where he was advised to modify his style and story to be more suitable for Weekly Shōnen Jump. He declined and decided instead to take it to the Weekly Shōnen Magazine department at Kodansha Ltd.[7]

In 2008, he applied for the 80th Weekly Shōnen Magazine Freshman Manga Award, where his work Heart Break One was given the Special Encouragement Award. His other work, Orz, was chosen as a selected work in the same contest the following year.

In 2009, his first serial work, Attack on Titan, started in the monthly Bessatsu Shōnen Magazine. It won the Shōnen category of the 35th Kodansha Manga Award in 2011,[8] and was nominated for both the 4th annual Manga Taishō award and the 16th annual Tezuka Osamu Cultural Prize.[9][10] Attack on Titan is released in English by Kodansha USA and has inspired five spin-off manga series, three light novel series, a televised anime adaptation, several visual novels and video games, and a two part live-action film. In November 2022, Isayama made his first-ever appearance in the United States at Anime NYC, an anime convention in New York City. The resort Bungo Oyama Hibiki no Sato in his hometown of Ōyama, ran a free exhibit displaying copies of Isayama's manuscripts for the manga in 2013.[5] A special Attack on Titan event was held in Hita on November 1, 2014, with Isayama and approximately 2,500 spectators attending. The following day, Isayama gave a speech at the Patria Hita cultural hall and was named the Tourism Ambassador of Hita by the city's mayor Keisuke Harada.[11] In December 2018, he announced in his blog that he had gotten married earlier that year.[1]</h4>
@endsection
